### ISSUE TITLE
What is module param in the method? 

### ISSUE THREAD

**Issue by rahilzebpay** [input-output-hk/js-cardano-wasm#12]
```
export const publicKeyToAddress = (module, xpub, payload) => {
  const bufxpub    = newArray(module, xpub);
  const bufpayload = newArray(module, payload);
  const bufaddr    = newArray0(module, 1024);

  let rs = module.wallet_public_to_address(bufxpub, bufpayload, payload.length, bufaddr);
  let addr = copyArray(module, bufaddr, rs);

  module.dealloc(bufaddr);
  module.dealloc(bufpayload);
  module.dealloc(bufxpub);

  return addr;
};
```

Thanks.

**Comment by NicolasDP** [comment]
it is the Wasm module. It is passed as parameter. I believe it was an attempt to leverage that we needed some time to load the wasm module.

@DominikGuzei migth be able to help here.

**Comment by rahilzebpay** [comment]
Thanks. I got that part. 
So now I load the module and pass it to the function. 

Just wanted to confirm. This library designed to work on browsers right? 
I was actually trying to run it on Node.js but ended up getting invalid addresses.

**Comment by NicolasDP** [comment]
if you are trying to recreates Daedalus addresses this is not possible with this library (yet). We may spend some time allowing compatibility in the future. see #5 

I guess we can close this issue then.

**Comment by NicolasDP** [comment]
It depends mainly on the kind of the kind of address derivation you want to use. For now most of the APIs you see are very low level and might change or disappear in the future.

##### Please, keep in mind that all of this library is a _Work in Progress_ and that it is not tested for _production environment_ (i.e. mainnet).

If you are using bip44 and sequential addresses, I suggest you use the [Wallet](https://github.com/input-output-hk/js-cardano-wasm/blob/master/js/Wallet.js) module for generating new addresses.
