### ISSUE TITLE
broken package.json for cardano-wallet

### ISSUE THREAD

**Issue by roccomuso** [input-output-hk/js-cardano-wasm#47]
*package.json* in `cardano-wallet` npm module is missing the "main" key, so no pointing to the js file resulting in `Error: Cannot find module 'cardano-wallet'` when importing the npm module.

It should also be transpiled, since it's using new syntax. I'm assuming something went wrong during build process.

**Comment by NicolasDP** [comment]
Thanks for reporting your issue (and experimenting with these new bindings).

Here is an example on how one could use the project in an application:

https://github.com/primetype/cardano-wallet-example-js

I hope this helps.

**Comment by NicolasDP** [comment]
Thanks so much. So actually what was published was for browser. I have changed this so it is `nodejs` compatible now.

`npm i --save cardano-wallet@0.2.2` is bundled for nodejs.
